AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy backend

Parameters:
  FastApiPort:
    Type: String
    Default: 8000
    NoEcho: true
  FastApiHost:
    Type: String
    Default: "0.0.0.0"
    NoEcho: true
  PostgresPort:
    Type: String
    Default: 5432
    NoEcho: true
  PostgresDbName:
    Type: String
  PostgresUser:
    Type: String
  PostgresPassword:
    Type: String

Resources:

  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/backend-service
      RetentionInDays: 7

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: backend-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: arn:aws:iam::863518442971:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: backend
          Image: 863518442971.dkr.ecr.us-east-1.amazonaws.com/awspython-backend
          PortMappings:
            - ContainerPort: 8000
          Environment:
            - Name: FASTAPI_PORT
              Value: !Ref FastApiPort
            - Name: FASTAPI_HOST
              Value: !Ref FastApiHost
            - Name: POSTGRES_HOST
              Value: !ImportValue my-db-host-v2
            - Name: POSTGRES_PORT
              Value: !Ref PostgresPort
            - Name: POSTGRES_DB_NAME
              Value: !Ref PostgresDbName
            - Name: POSTGRES_USER
              Value: !Ref PostgresUser
            - Name: POSTGRES_PASSWORD
              Value: !Ref PostgresPassword
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/backend-service
              awslogs-region: us-east-1
              awslogs-stream-prefix: backend

  BackendService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue my-ecs-cluster-v2
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref BackendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue my-network-private-subnet-1-id-v2
            - !ImportValue my-network-private-subnet-2-id-v2
          SecurityGroups:
            - !ImportValue my-network-backend-sg-v2
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: 8000
          TargetGroupArn: !ImportValue my-network-backend-tg-v2

# NOTE:
# Ensure the IAM Role ecsTaskExecutionRole includes:
#   logs:CreateLogStream
#   logs:PutLogEvents
# for the log group /ecs/backend-service
