name: awspython
services:
  database:
    image: postgres:14.5
    hostname: ${POSTGRES_HOST}
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433

  backend:
    build:
      context: ../
      dockerfile: .docker/Dockerfile.backend
    env_file:
      - ./.env
    ports:
      # крче нельзя их подставить из env
      - "8000:8000"  # Only the left side (host) can use a variable
    depends_on:
      - database

  frontend:
    build:
      context: ../
      dockerfile: .docker/Dockerfile.frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    depends_on:
      - backend
      - database
    ports:
      - "3000:3000"
    env_file:
      - ./.env

  # frontreact:
  #   build:
  #     context: ../
  #     dockerfile: .docker/Dockerfile.frontreact
  #   depends_on:
  #     - backend
  #     - database
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./.env

volumes:
  postgres_data:

