name: Backend App Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.infra/**'
  workflow_run:
    workflows: ["Network/VPC Deployment"]
    types: [completed]
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ${{ secrets.ECR_BACKEND }}

jobs:
  backend-build-and-publish:
    name: Backend Build and Publish
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push backend image to Amazon ECR
        id: build-image
        run: |
          docker build -t $ECR_REPOSITORY:latest -f .docker/Dockerfile.backend .
          docker push $ECR_REPOSITORY:latest

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: production
    needs:
      - backend-build-and-publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy backend
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: my-backend-stack-v2
          template: .infra/5_backend.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            PostgresPort=${{ secrets.POSTGRES_PORT }},
            PostgresUser=${{ secrets.POSTGRES_USER }},
            PostgresPassword=${{ secrets.POSTGRES_PASSWORD }},
            PostgresDbName=${{ secrets.POSTGRES_DB_NAME }}
